name: Check Azure Status

on:
  check_suite:
    types: [completed]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        # set id so we can grab the output in later steps
        # like that: ${{steps.status.outputs.status}}
        id: status
        uses: ./.github/workflows/azure
